spring.jpa:
  database: postgresql
  show-sql: true

server:
  port: 8180
  servlet:
    context-path: /app
spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: 130592
    url: jdbc:postgresql://localhost:5432/postgres
